In [7]:
# Underwriting Issuance Analysis (Notebook Version)

import pandas as pd
import numpy as np
from datetime import datetime
from pathlib import Path

import plotly.express as px
import plotly.graph_objects as go

from io import BytesIO
import openpyxl

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 120)

In [8]:
# 1. Configure data source

# Option A: Use default CSV from the data folder
DATA_PATH = Path("data/auto_issuance_synthetic_1year_10000rows.csv")

# Option B: Manually point to another CSV/Excel file
# DATA_PATH = Path("path/to/your/file.csv")
# DATA_PATH = Path("path/to/your/file.xlsx")

print(f"Using data file: {DATA_PATH}")

if not DATA_PATH.exists():
    raise FileNotFoundError(f"Data file not found: {DATA_PATH}")

# Helper to load CSV or Excel

def load_data(path: Path) -> pd.DataFrame:
    if path.suffix.lower() == ".csv":
        return pd.read_csv(path, low_memory=False)
    elif path.suffix.lower() in {".xlsx", ".xls"}:
        return pd.read_excel(path, engine="openpyxl")
    else:
        raise ValueError(f"Unsupported file type: {path.suffix}")

original_df = load_data(DATA_PATH)
print("Rows:", len(original_df))
original_df.head()

Using data file: data/auto_issuance_synthetic_1year_10000rows.csv
Rows: 10000

,requestId,opportunityId,ambiguousOpportunityIndicator,processId,requestTypeCode,requestTypeDescription,requestEffectiveDate,statusCode,statusDescription,onHoldReasonCode,onHoldReasonDescription,writeOutReasonCode,writeOutReasonDescription,bgiCode,bgiDescription,lineOfBusinessCode,lineOfBusinessDescription,priorityCode,priorityDescription,accountSystemOfRecordCode,accountSystemOfRecordDescription,salesOfficeCode,salesOfficeDescription,salesRepCode,salesRepDescription,underwritingSegmentCode,underwritingSegmentDescription,regionCode,regionDescription,divisionCode,divisionDescription,targetDateTime,negotiatedTargetDateTime,createDateTime,completedDateTime,endDateTime,receivedDateTime,Aging,standardSLAViolationIndicator,rushSLAViolationIndicator,policyNumber,policyName,policyEffectiveDate,policyExpirationDate,quoteExpirationDate,raterUserIdentificationNumber,raterFullName,assigneeType,localAccountId,accountNumber,midwayCustomerNumber,CCOProspectIdNumber,underwriter,accountAnalyst,accountName,onHoldDatesHistory,Last Hold,offHoldDatesHistory,onHoldReasonCodesHistory,Hold Time,onHoldReasonDescriptionsHistory,Booking Validation HT,EPA-Validate Policy Review HT,Large Audit Variance HT,Other HT,System Issues HT,Underwriting Request HT,Write-Out HT,No of Holds,Types of Case,Booking Validation,EPA-Validate Policy Review,Large Audit Variance,Other,System Issues,Underwriting Request,Write-Out,TAT,TAT Bands,writeOutReasonCodesHistory,writeOutReasonDescriptionsHistory,reRateCode,reRateReason,versions,agentBrokerNum,estimatedAnnualPremium,writeOutCreateDate,writeOutCreator,writeOutReasonCodes,writeOutDescriptions,writeOutRecipientId,writeOutRecipientName,writeOutCCId,writeOutCCName,createdByName,createdById,rpcId,rushReasonDescription,endorsementDescription,underwriterName,accountAnalystName,bureauState,bureauNumber,numberOfLocations,volume,Gross_TAT_Days,Net_TAT_Days,SLA_Status,fieldInError,editErrorNumber,editErrorMessage,ncicIDNumber,underwritingSubsegmentCode,underwritingSubsegmentDescription,receivedInUnderwritingDate,replacementReasonCode,replacementReasonDescription,errorCode,asrRO,asrVIN,modEffectiveDate,revisedMod,revisedModDate,eibIdentifier,ledgerNumber,origin,prelimIndicator,batchRunId,numberOfRisks,numberOfLocations__2,transactionId,editReason,sequence,cancellationReason,subReason,flags,AgentBrokerName,asrRO__2,asrVIN__2,modEffectiveDate__2,revisedModType,revisedModFactor,eibIdentifier__2,ledgerNumber__2,origin__2,prelimIndicator__2,batchRunNumber,numberOfTransactions,numberOfRuns,transactionType,editReason__2,sequenceNumbers,cancellationTypeDescription,reasonForCancellationDescription,subReasonForCancellationDescription,flags__2,AgentBrokerStateCode,AgentBrokerName__2,ManualTransaction,BartVerified,PolicyView,PremiumImpacting,BartTransactionCreatedDate,NumberOfVehicles,NumberOfClaims,WriteOutText,CurrentModType,CurrentModFactor,NumberOfPotentialPolicies,ePolicyB2B,ePolicyNonB2B,TIV
0,REQXAJI0Y6DPBHS,OPPAHXTHV3A3Z,0,PRCMF8MDD4V,CAN,"Endorsement, needs approval, urgent",2025-01-23,HOLD,"On hold, awaiting info",NaN,NaN,NaN,"Write-out reason, follow-up required, add notes",BG2,"Business group, follow-up required, add notes",COMM,"Commercial, fleet",P3,"Low, backlog",LEG,"System of record, follow-up required, add notes",SO16,"Sales office, pending review",SR162,"Sales rep, follow-up required, add notes",STD,"Standard, retail",NE,North East,D1,Division 1,2025-01-27 00:01:34,2025-01-29 00:01:34,2025-01-24 00:01:34,NaN,NaN,2025-01-25 00:01:34,NaN,NaN,NaN,PN48840994,Auto Secure,2025-02-16,2026-02-16,2025-02-13,R02DGTFGQ5,Aditya Roy,Underwriter,LAB94874FR,AC4586084,MC520521,CCO161483,Reyansh Das,Aarav Das,"GreenLeaf Foods, follow-up required, add notes",NaN,NaN,NaN,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,Underwriting Request,0,0,0,0,0,1,0,NaN,NaN,WO_D,"Write-out reason, needs approval, urgent",RR1,"Re-rate requested, ok",7,AB804314,200.00,2025-11-29 11:28:57,Aarohi Roy,NaN,NaN,NaN,NaN,NaN,NaN,Ishaan Iyer,UCATVAZCC,RPCBLSKRT05,NaN,NaN,Rohan Das,Anika Patel,CA,7065,1,1.12,NaN,NaN,Open,NaN,E489,"Validation failed, follow-up required, add notes",NCICZFK8UT,STD_B,Standard B,2025-01-25,REP2,"Replacement reason, follow-up required, add notes",E489,ROMYZYCWTI,QJ7YHL1C32OC6UZHR,2025-11-26,1.120,2025-08-23,EIBFF0T0PVN9,LEDER14FFY,Agent,0,BATCHNVQJT7,3,1,TXNYE511MKFAZ,"Coverage change, endorsement",17,"Non-payment, customer",Missing docs,NaN,Rohan Patel,ROMYZYCWTI,QJ7YHL1C32OC6UZHR,2025-11-26,Projected,1.202,EIBFF0T0PVN9,LEDER14FFY,Agent,0,BRNVF1T2TA,1,3,Endorsement,"Coverage change, endorsement","2,8,24,57","Underwriting initiated, cancel","Reason for cancellation, needs approval, urgent","Sub reason, pending review",NaN,NJ,Rohan Patel,0,0,Agent view,1,2025-02-05 17:49:08,3,0,"Write-out notes, follow-up required, add notes",Revised,0.907,0,0,1,208084.32
1,REQS4F8CGVYIE6I,OPPVWPVS7HZIO,1,PRCYKL1CQ99,CAN,"New Business, pending review",2025-02-07,INPR,"In progress, processing",SYS,"System issue, retry later",NaN,NaN,BG1,"Business group, needs approval, urgent",HOME,"Homeowners, bundled",P3,"Low, backlog",LEG,"System of record, pending review",SO81,"Sales office, needs approval, urgent",SR968,"Sales rep, pending review",STD,"Standard, retail",MW,Midwest,D3,Division 3,2025-02-14 02:21:32,2025-02-12 02:21:32,2025-02-07 18:21:32,NaN,NaN,2025-02-08 02:21:32,NaN,NaN,NaN,PN28024248,RoadShield,2025-01-15,2026-01-15,2025-02-20,RQ2Y9V86WZ,Aarohi Das,System,LA60RJIW1S,AC5013879,MC387936,CCO561239,Aditya Mehta,Rohan Iyer,"GreenLeaf Foods, ok",2025-02-08 20:21:32,2025-02-08 20:21:32,2025-02-10 11:21:32,SYS,39.0,"System issue, retry later",0.0,0.0,0.0,39.0,0.0,0.0,0.0,1,Other,0,0,0,1,0,0,0,NaN,NaN,NaN,NaN,RR2,"Re-rate requested, ok",11,AB989208,1610.40,2025-03-05 23:57:19,Aarohi Nair,"WO_D,WO_B","Desc, follow-up required, add notes,Desc, ok",UTGXN0GUO,Aarav Nair,UKPUXQPHR,Reyansh Patel,Aditya Nair,USWM31YIH,RPCAIR4COWG,NaN,NaN,Saanvi Chatterjee,Aditya Gupta,IL,4335,1,0.66,NaN,NaN,Open,modEffectiveDate,E259,"Validation failed, ok",NCICFNFHOL,STD_A,Standard A,2025-02-08,REP3,NaN,E259,ROY4SJ6BW3,BME9FPZUE8YFBNTPB,2025-07-06,0.697,2025-01-21,EIB6HID25OWF,LED75935A0,Batch,1,BATCH253J2D,2,1,TXN54I3QK2IAG,"Coverage change, endorsement",9,NaN,Fraud check,"Audit, review required",Aarohi Das,ROY4SJ6BW3,BME9FPZUE8YFBNTPB,2025-07-06,Projected,0.874,EIB6HID25OWF,LED75935A0,Batch,1,BRN9T7E8G8,2,1,Endorsement,"Coverage change, endorsement",7,"System initiated, cancel","Reason for cancellation, ok","Sub reason, ok","Audit, review required",TX,Aarohi Das,0,1,Agent view,0,2025-05-11 01:45:27,1,1,"Write-out notes, needs approval, urgent",NaN,1.120,0,1,0,195942.52
2,REQHP6VZ41NAM14,OPP8P0TVHHPBM,1,PRCYOFQEWAO,REN,"Endorsement, follow-up required, add notes",2025-10-16,INPR,"In progress, processing",NaN,NaN,NaN,NaN,BG3,"Business group, ok",COMM,"Commercial, fleet",P2,"Medium, standard",LEG,"System of record, follow-up required, add notes",SO66,"Sales office, ok",SR288,"Sales rep, pending review",PREF,"Preferred, low risk",W,West,D2,Division 2,2025-10-21 02:46:05,2025-10-22 02:46:05,2025-10-16 23:46:05,NaN,NaN,2025-10-18 02:46:05,NaN,NaN,NaN,PN43859311,Auto Secure,2025-10-16,2026-10-16,2025-10-24,RJ5ECRUYF3,Rohan Verma,Analyst,LAE1V2ISQP,AC8194570,MC420214,CCO696251,Riya Sharma,Riya Mehta,"Acme Motors, needs approval, urgent",NaN,NaN,NaN,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,EPA-Validate Policy Review,0,1,0,0,0,0,0,NaN,NaN,WO_C,"Write-out reason, follow-up required, add notes",RR2,"Re-rate requested, ok",12,AB575786,1144.09,2025-05-19 09:16:14,Vihaan Mehta,NaN,NaN,NaN,NaN,NaN,NaN,Saanvi Verma,U08YG0JV1,RPCV93KMKZE,NaN,"Endorsement applied, pending review",Ayaan Nair,Aditya Gupta,NY,1508,1,2.31,NaN,NaN,Open,modEffectiveDate,E153,"Validation failed, needs approval, urgent",NCICITFOYQ,HIGH_A,High Risk A,2025-10-18,NaN,NaN,E153,RO8HAFEYUH,Z1GV0E38DALY8OZCY,2025-11-18,0.993,2025-05-05,EIBD14VE92MP,LEDNSM43D8,CSR,0,BATCHP08J3T,2,1,TXNRP0J43D5IQ,"System recalculation, batch",11,NaN,Duplicate quote,"Audit, review required",Reyansh Roy,RO8HAFEYUH,Z1GV0E38DALY8OZCY,2025-11-18,Current,1.078,EIBD14VE92MP,LEDNSM43D8,CSR,0,BRNMJKV5US,2,1,Renewal,"System recalculation, batch",16,"System initiated, cancel","Reason for cancellation, follow-up required, a...","Sub reason, needs approval, urgent","Audit, review required",TX,Reyansh Roy,1,1,Summary,0,2025-05-31 07:25:44,2,0,NaN,Revised,1.148,0,1,0,265423.15
3,REQZZQY72WX7PTX,OPP63CFL0UKEY,1,PRCZ7SRCBPL,CAN,"Endorsement, follow-up required, add notes",2025-05-09,INPR,"In progress, processing",DOC,"Missing documents, customer to provide",WO_B,"Write-out reason, follow-up required, add notes",BG2,"Business group, pending review",COMM,"Commercial, fleet",P2,"Medium, standard",GW,"System of record, follow-up required, add notes",SO83,"Sales office, ok",SR688,"Sales rep, ok",STD,"Standard, retail",W,West,D3,Division 3,2025-05-20 14:58:14,2025-05-18 14:58:14,2025-05-09 02:58:14,NaN,NaN,2025-05-10 14:58:14,NaN,NaN,NaN,PN22246348,FleetGuard,2025-05-01,2026-05-01,2025-06-11,R9K9XJUY0B,Riya Mehta,System,LA361I2HGJ,AC3294774,MC758765,CCO201883,Vivaan Nair,Ira Sharma,"Metro Services, ok",2025-05-10 20:58:14,2025-05-10 20:58:14,2025-05-13 09:58:14,DOC,61.0,"Missing documents, customer to provide",0.0,0.0,0.0,61.0,0.0,0.0,0.0,1,Other,0,0,0,1,0,0,0,NaN,NaN,WO_B,"Write-out reason, pending review",RR3,"Re-rate requested, ok",6,AB753534,2434.10,2025-12-21 12:41:05,Saanvi Patel,"WO_D,WO_B","Desc, follow-up required, add notes,Desc, pend...",UWIYKID91,Vihaan Roy,UFKBLCMPI,Diya Khan,Reyansh Gupta,UGVNYRUIW,RPCQY6QKTC8,NaN,NaN,Arjun Verma,Rohan Singh,CA,6403,1,1.41,NaN,NaN,Open,ratingError,NaN,NaN,NCIC0GET8T,HIGH_A,High Risk A,2025-05-10,REP2,NaN,NaN,ROORXO1BDJ,E153A5QBSWRPBJEK5,2025-09-06,0.609,2025-03-04,EIBBW2ZLAOI4,LEDE8XF7KZ,CSR,1,BATCH9ITN7S,1,1,TXN55J2O7S3KK,"System recalculation, batch",5,"Underwriting decline, risk",Missing docs,"Rush, expedite",Aadhya Singh,ROORXO1BDJ,E153A5QBSWRPBJEK5,2025-09-06,Projected,1.116,EIBBW2ZLAOI4,LEDE8XF7KZ,CSR,1,BRN1N759IN,3,2,Cancellation,"System recalculation, batch",21,"System initiated, cancel","Reason for cancellation, follow-up required, a...","Sub reason, follow-up required, add notes","Rush, expedite",NJ,Aadhya Singh,1,0,Summary,1,2025-02-21 14:06:33,1,0,NaN,Current,1.178,0,0,1,279813.71
4,REQJ3R30ME8F840,OPP982N2ATQYY,1,PRCV37DIA5U,NB,"New Business, pending review",2025-11-09,NEW,"New, created",NaN,NaN,NaN,NaN,BG1,"Business group, follow-up required, add notes",COMM,"Commercial, fleet",P2,"Medium, standard",LEG,"System of record, follow-up required, add notes",SO53,"Sales office, needs approval, urgent",SR478,"Sales rep, ok",STD,"Standard, retail",NE,North East,D1,Division 1,2025-11-15 15:24:04,2025-11-18 15:24:04,2025-11-09 10:24:04,NaN,NaN,2025-11-10 15:24:04,NaN,NaN,NaN,PN62163160,FleetGuard,2025-11-02,2026-11-02,2025-12-20,RZ1UDBFWYJ,Diya Roy,System,LAOHSMDYVS,AC6174418,MC147623,CCO331230,Anaya Khan,Vivaan Sharma,"BlueSky Logistics, ok",NaN,NaN,NaN,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,Underwriting Request,0,0,0,0,0,1,0,NaN,NaN,WO_D,"Write-out reason, ok",RR2,"Re-rate requested, ok",3,AB820184,1540.89,2025-08-31 02:05:53,Aditya Verma,WO_A,"Desc, ok",U3UVULEMX,Diya Mehta,UBKLDSFR4,Aadhya Chatterjee,Aadhya Verma,U1U3493WX,RPCA73JGZLM,NaN,"Endorsement applied, needs approval, urgent",Ayaan Gupta,Kabir Nair,MA,2622,2,1.09,NaN,NaN,Open,editErrorMessage,NaN,NaN,NCICLA0GNZ,STD_B,Standard B,2025-11-10,REP2,"Replacement reason, pending review",NaN,RO4W7KYHQI,N9N6XCJ883DHX8BM9,2025-10-17,1.259,2025-04-16,EIBC1HH5LF6A,LED4FEJGXA,Portal,1,BATCH2ILGB0,2,2,TXNS0R2SDS8B2,"Coverage change, endorsement",15,NaN,NaN,"Rush, expedite",Anaya Das,RO4W7KYHQI,N9N6XCJ883DHX8BM9,2025-10-17,Projected,1.059,EIBC1HH5LF6A,LED4FEJGXA,Portal,1,BRNDZP6LFE,1,2,Endorsement,"Coverage change, endorsement","19,30,34,39","System initiated, cancel","Reason for cancellation, pending review","Sub reason, pending review","Rush, expedite",FL,Anaya Das,0,1,Full view,0,2025-07-31 10:52:29,3,0,NaN,Revised,0.993,1,0,1,390817.93

In [9]:
# 2. Helper functions for parsing and calculations

def parse_separated_values(value, separator=None):
    """Parse values that may be separated by ', ' or '|' into a list."""
    if pd.isna(value) or value == "":
        return []

    value = str(value).strip()
    if separator:
        separators = [separator]
    else:
        if "|" in value:
            separators = ["|"]
        elif ", " in value:
            separators = [", "]
        else:
            return [value] if value else []

    result = []
    for sep in separators:
        if sep in value:
            result = [v.strip() for v in value.split(sep) if v.strip()]
            break

    return result if result else ([value] if value else [])


def calculate_aging(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    df["createDateTime"] = pd.to_datetime(df["createDateTime"], errors="coerce")
    df["completedDateTime"] = pd.to_datetime(df["completedDateTime"], errors="coerce")

    mask = df["completedDateTime"].isna()
    df.loc[mask, "Aging_Days"] = (datetime.now() - df.loc[mask, "createDateTime"]).dt.days
    df.loc[~mask, "Aging_Days"] = np.nan
    return df


def classify_case_type(on_hold_reasons) -> str:
    reasons = parse_separated_values(on_hold_reasons)
    if len(reasons) == 0:
        return "Straight Through"
    elif len(reasons) == 1:
        return "One Touch"
    else:
        return f"Multi Hold ({len(reasons)} touches)"


def calculate_holding_times(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    holding_times_list = []

    for _, row in df.iterrows():
        on_hold_dates = parse_separated_values(row.get("onHoldDatesHistory", ""))
        off_hold_dates = parse_separated_values(row.get("offHoldDatesHistory", ""))

        on_hold_dates_parsed = [
            pd.to_datetime(d, errors="coerce") for d in on_hold_dates
        ]
        on_hold_dates_parsed = [d for d in on_hold_dates_parsed if pd.notna(d)]

        off_hold_dates_parsed = [
            pd.to_datetime(d, errors="coerce") for d in off_hold_dates
        ]
        off_hold_dates_parsed = [d for d in off_hold_dates_parsed if pd.notna(d)]

        hold_times = []
        for i, on_date in enumerate(on_hold_dates_parsed):
            if i < len(off_hold_dates_parsed):
                off_date = off_hold_dates_parsed[i]
                if pd.notna(on_date) and pd.notna(off_date):
                    hold_times.append((off_date - on_date).days)
            else:
                if pd.notna(on_date):
                    hold_times.append((datetime.now() - on_date).days)

        holding_times_list.append(hold_times)

    df["HoldingTimes"] = holding_times_list
    df["TotalHoldingTime"] = df["HoldingTimes"].apply(lambda x: sum(x) if x else 0)
    df["NumberOfTouches"] = df["HoldingTimes"].apply(lambda x: len(x) if x else 0)
    return df


def calculate_tat(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    df["createDateTime"] = pd.to_datetime(df["createDateTime"], errors="coerce")
    df["completedDateTime"] = pd.to_datetime(df["completedDateTime"], errors="coerce")

    mask = df["completedDateTime"].notna()
    df.loc[mask, "TAT_Days"] = (
        df.loc[mask, "completedDateTime"] - df.loc[mask, "createDateTime"]
    ).dt.days
    df.loc[~mask, "TAT_Days"] = np.nan
    return df


def create_tat_bucket(tat_days):
    if pd.isna(tat_days):
        return None
    if tat_days <= 5:
        return "0-5 days"
    elif tat_days <= 7:
        return "5-7 days"
    else:
        return "7+ days"

In [10]:
# 3. Process data (mirrors Streamlit app logic)

# Work on a copy for processing
df = original_df.copy()

# Basic calculations
df = calculate_aging(df)

df["CaseType"] = df["onHoldReasonDescriptionsHistory"].apply(classify_case_type)

df = calculate_holding_times(df)

df = calculate_tat(df)

df["TAT_Bucket"] = df["TAT_Days"].apply(create_tat_bucket)

# Month / seasonality
if "createDateTime" in df.columns:
    df["createDateTime"] = pd.to_datetime(df["createDateTime"], errors="coerce")
    df["Month"] = df["createDateTime"].dt.to_period("M")
    df["Month_Str"] = df["Month"].astype(str)

# Hold category (Straight / Single / Multi)
df["HoldCategory"] = df["CaseType"].apply(
    lambda x: "Straight Through" if x == "Straight Through"
    else "Single Hold" if x == "One Touch"
    else "Multi Hold"
)

print("Processed rows:", len(df))
df.head()

Processed rows: 10000

,requestId,opportunityId,ambiguousOpportunityIndicator,processId,requestTypeCode,requestTypeDescription,requestEffectiveDate,statusCode,statusDescription,onHoldReasonCode,onHoldReasonDescription,writeOutReasonCode,writeOutReasonDescription,bgiCode,bgiDescription,lineOfBusinessCode,lineOfBusinessDescription,priorityCode,priorityDescription,accountSystemOfRecordCode,accountSystemOfRecordDescription,salesOfficeCode,salesOfficeDescription,salesRepCode,salesRepDescription,underwritingSegmentCode,underwritingSegmentDescription,regionCode,regionDescription,divisionCode,divisionDescription,targetDateTime,negotiatedTargetDateTime,createDateTime,completedDateTime,endDateTime,receivedDateTime,Aging,standardSLAViolationIndicator,rushSLAViolationIndicator,policyNumber,policyName,policyEffectiveDate,policyExpirationDate,quoteExpirationDate,raterUserIdentificationNumber,raterFullName,assigneeType,localAccountId,accountNumber,midwayCustomerNumber,CCOProspectIdNumber,underwriter,accountAnalyst,accountName,onHoldDatesHistory,Last Hold,offHoldDatesHistory,onHoldReasonCodesHistory,Hold Time,onHoldReasonDescriptionsHistory,Booking Validation HT,EPA-Validate Policy Review HT,Large Audit Variance HT,Other HT,System Issues HT,Underwriting Request HT,Write-Out HT,No of Holds,Types of Case,Booking Validation,EPA-Validate Policy Review,Large Audit Variance,Other,System Issues,Underwriting Request,Write-Out,TAT,TAT Bands,writeOutReasonCodesHistory,writeOutReasonDescriptionsHistory,reRateCode,reRateReason,versions,agentBrokerNum,estimatedAnnualPremium,writeOutCreateDate,writeOutCreator,writeOutReasonCodes,writeOutDescriptions,writeOutRecipientId,writeOutRecipientName,writeOutCCId,writeOutCCName,createdByName,createdById,rpcId,rushReasonDescription,endorsementDescription,underwriterName,accountAnalystName,bureauState,bureauNumber,numberOfLocations,volume,Gross_TAT_Days,Net_TAT_Days,SLA_Status,fieldInError,editErrorNumber,editErrorMessage,ncicIDNumber,underwritingSubsegmentCode,underwritingSubsegmentDescription,receivedInUnderwritingDate,replacementReasonCode,replacementReasonDescription,errorCode,asrRO,asrVIN,modEffectiveDate,revisedMod,revisedModDate,eibIdentifier,ledgerNumber,origin,prelimIndicator,batchRunId,numberOfRisks,numberOfLocations__2,transactionId,editReason,sequence,cancellationReason,subReason,flags,AgentBrokerName,asrRO__2,asrVIN__2,modEffectiveDate__2,revisedModType,revisedModFactor,eibIdentifier__2,ledgerNumber__2,origin__2,prelimIndicator__2,batchRunNumber,numberOfTransactions,numberOfRuns,transactionType,editReason__2,sequenceNumbers,cancellationTypeDescription,reasonForCancellationDescription,subReasonForCancellationDescription,flags__2,AgentBrokerStateCode,AgentBrokerName__2,ManualTransaction,BartVerified,PolicyView,PremiumImpacting,BartTransactionCreatedDate,NumberOfVehicles,NumberOfClaims,WriteOutText,CurrentModType,CurrentModFactor,NumberOfPotentialPolicies,ePolicyB2B,ePolicyNonB2B,TIV,Aging_Days,CaseType,HoldingTimes,TotalHoldingTime,NumberOfTouches,TAT_Days,TAT_Bucket,Month,Month_Str,HoldCategory
0,REQXAJI0Y6DPBHS,OPPAHXTHV3A3Z,0,PRCMF8MDD4V,CAN,"Endorsement, needs approval, urgent",2025-01-23,HOLD,"On hold, awaiting info",NaN,NaN,NaN,"Write-out reason, follow-up required, add notes",BG2,"Business group, follow-up required, add notes",COMM,"Commercial, fleet",P3,"Low, backlog",LEG,"System of record, follow-up required, add notes",SO16,"Sales office, pending review",SR162,"Sales rep, follow-up required, add notes",STD,"Standard, retail",NE,North East,D1,Division 1,2025-01-27 00:01:34,2025-01-29 00:01:34,2025-01-24 00:01:34,NaT,NaN,2025-01-25 00:01:34,NaN,NaN,NaN,PN48840994,Auto Secure,2025-02-16,2026-02-16,2025-02-13,R02DGTFGQ5,Aditya Roy,Underwriter,LAB94874FR,AC4586084,MC520521,CCO161483,Reyansh Das,Aarav Das,"GreenLeaf Foods, follow-up required, add notes",NaN,NaN,NaN,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,Underwriting Request,0,0,0,0,0,1,0,NaN,NaN,WO_D,"Write-out reason, needs approval, urgent",RR1,"Re-rate requested, ok",7,AB804314,200.00,2025-11-29 11:28:57,Aarohi Roy,NaN,NaN,NaN,NaN,NaN,NaN,Ishaan Iyer,UCATVAZCC,RPCBLSKRT05,NaN,NaN,Rohan Das,Anika Patel,CA,7065,1,1.12,NaN,NaN,Open,NaN,E489,"Validation failed, follow-up required, add notes",NCICZFK8UT,STD_B,Standard B,2025-01-25,REP2,"Replacement reason, follow-up required, add notes",E489,ROMYZYCWTI,QJ7YHL1C32OC6UZHR,2025-11-26,1.120,2025-08-23,EIBFF0T0PVN9,LEDER14FFY,Agent,0,BATCHNVQJT7,3,1,TXNYE511MKFAZ,"Coverage change, endorsement",17,"Non-payment, customer",Missing docs,NaN,Rohan Patel,ROMYZYCWTI,QJ7YHL1C32OC6UZHR,2025-11-26,Projected,1.202,EIBFF0T0PVN9,LEDER14FFY,Agent,0,BRNVF1T2TA,1,3,Endorsement,"Coverage change, endorsement","2,8,24,57","Underwriting initiated, cancel","Reason for cancellation, needs approval, urgent","Sub reason, pending review",NaN,NJ,Rohan Patel,0,0,Agent view,1,2025-02-05 17:49:08,3,0,"Write-out notes, follow-up required, add notes",Revised,0.907,0,0,1,208084.32,383.0,Straight Through,[],0,0,NaN,None,2025-01,2025-01,Straight Through
1,REQS4F8CGVYIE6I,OPPVWPVS7HZIO,1,PRCYKL1CQ99,CAN,"New Business, pending review",2025-02-07,INPR,"In progress, processing",SYS,"System issue, retry later",NaN,NaN,BG1,"Business group, needs approval, urgent",HOME,"Homeowners, bundled",P3,"Low, backlog",LEG,"System of record, pending review",SO81,"Sales office, needs approval, urgent",SR968,"Sales rep, pending review",STD,"Standard, retail",MW,Midwest,D3,Division 3,2025-02-14 02:21:32,2025-02-12 02:21:32,2025-02-07 18:21:32,NaT,NaN,2025-02-08 02:21:32,NaN,NaN,NaN,PN28024248,RoadShield,2025-01-15,2026-01-15,2025-02-20,RQ2Y9V86WZ,Aarohi Das,System,LA60RJIW1S,AC5013879,MC387936,CCO561239,Aditya Mehta,Rohan Iyer,"GreenLeaf Foods, ok",2025-02-08 20:21:32,2025-02-08 20:21:32,2025-02-10 11:21:32,SYS,39.0,"System issue, retry later",0.0,0.0,0.0,39.0,0.0,0.0,0.0,1,Other,0,0,0,1,0,0,0,NaN,NaN,NaN,NaN,RR2,"Re-rate requested, ok",11,AB989208,1610.40,2025-03-05 23:57:19,Aarohi Nair,"WO_D,WO_B","Desc, follow-up required, add notes,Desc, ok",UTGXN0GUO,Aarav Nair,UKPUXQPHR,Reyansh Patel,Aditya Nair,USWM31YIH,RPCAIR4COWG,NaN,NaN,Saanvi Chatterjee,Aditya Gupta,IL,4335,1,0.66,NaN,NaN,Open,modEffectiveDate,E259,"Validation failed, ok",NCICFNFHOL,STD_A,Standard A,2025-02-08,REP3,NaN,E259,ROY4SJ6BW3,BME9FPZUE8YFBNTPB,2025-07-06,0.697,2025-01-21,EIB6HID25OWF,LED75935A0,Batch,1,BATCH253J2D,2,1,TXN54I3QK2IAG,"Coverage change, endorsement",9,NaN,Fraud check,"Audit, review required",Aarohi Das,ROY4SJ6BW3,BME9FPZUE8YFBNTPB,2025-07-06,Projected,0.874,EIB6HID25OWF,LED75935A0,Batch,1,BRN9T7E8G8,2,1,Endorsement,"Coverage change, endorsement",7,"System initiated, cancel","Reason for cancellation, ok","Sub reason, ok","Audit, review required",TX,Aarohi Das,0,1,Agent view,0,2025-05-11 01:45:27,1,1,"Write-out notes, needs approval, urgent",NaN,1.120,0,1,0,195942.52,368.0,Multi Hold (2 touches),[1],1,1,NaN,None,2025-02,2025-02,Multi Hold
2,REQHP6VZ41NAM14,OPP8P0TVHHPBM,1,PRCYOFQEWAO,REN,"Endorsement, follow-up required, add notes",2025-10-16,INPR,"In progress, processing",NaN,NaN,NaN,NaN,BG3,"Business group, ok",COMM,"Commercial, fleet",P2,"Medium, standard",LEG,"System of record, follow-up required, add notes",SO66,"Sales office, ok",SR288,"Sales rep, pending review",PREF,"Preferred, low risk",W,West,D2,Division 2,2025-10-21 02:46:05,2025-10-22 02:46:05,2025-10-16 23:46:05,NaT,NaN,2025-10-18 02:46:05,NaN,NaN,NaN,PN43859311,Auto Secure,2025-10-16,2026-10-16,2025-10-24,RJ5ECRUYF3,Rohan Verma,Analyst,LAE1V2ISQP,AC8194570,MC420214,CCO696251,Riya Sharma,Riya Mehta,"Acme Motors, needs approval, urgent",NaN,NaN,NaN,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,EPA-Validate Policy Review,0,1,0,0,0,0,0,NaN,NaN,WO_C,"Write-out reason, follow-up required, add notes",RR2,"Re-rate requested, ok",12,AB575786,1144.09,2025-05-19 09:16:14,Vihaan Mehta,NaN,NaN,NaN,NaN,NaN,NaN,Saanvi Verma,U08YG0JV1,RPCV93KMKZE,NaN,"Endorsement applied, pending review",Ayaan Nair,Aditya Gupta,NY,1508,1,2.31,NaN,NaN,Open,modEffectiveDate,E153,"Validation failed, needs approval, urgent",NCICITFOYQ,HIGH_A,High Risk A,2025-10-18,NaN,NaN,E153,RO8HAFEYUH,Z1GV0E38DALY8OZCY,2025-11-18,0.993,2025-05-05,EIBD14VE92MP,LEDNSM43D8,CSR,0,BATCHP08J3T,2,1,TXNRP0J43D5IQ,"System recalculation, batch",11,NaN,Duplicate quote,"Audit, review required",Reyansh Roy,RO8HAFEYUH,Z1GV0E38DALY8OZCY,2025-11-18,Current,1.078,EIBD14VE92MP,LEDNSM43D8,CSR,0,BRNMJKV5US,2,1,Renewal,"System recalculation, batch",16,"System initiated, cancel","Reason for cancellation, follow-up required, a...","Sub reason, needs approval, urgent","Audit, review required",TX,Reyansh Roy,1,1,Summary,0,2025-05-31 07:25:44,2,0,NaN,Revised,1.148,0,1,0,265423.15,117.0,Straight Through,[],0,0,NaN,None,2025-10,2025-10,Straight Through
3,REQZZQY72WX7PTX,OPP63CFL0UKEY,1,PRCZ7SRCBPL,CAN,"Endorsement, follow-up required, add notes",2025-05-09,INPR,"In progress, processing",DOC,"Missing documents, customer to provide",WO_B,"Write-out reason, follow-up required, add notes",BG2,"Business group, pending review",COMM,"Commercial, fleet",P2,"Medium, standard",GW,"System of record, follow-up required, add notes",SO83,"Sales office, ok",SR688,"Sales rep, ok",STD,"Standard, retail",W,West,D3,Division 3,2025-05-20 14:58:14,2025-05-18 14:58:14,2025-05-09 02:58:14,NaT,NaN,2025-05-10 14:58:14,NaN,NaN,NaN,PN22246348,FleetGuard,2025-05-01,2026-05-01,2025-06-11,R9K9XJUY0B,Riya Mehta,System,LA361I2HGJ,AC3294774,MC758765,CCO201883,Vivaan Nair,Ira Sharma,"Metro Services, ok",2025-05-10 20:58:14,2025-05-10 20:58:14,2025-05-13 09:58:14,DOC,61.0,"Missing documents, customer to provide",0.0,0.0,0.0,61.0,0.0,0.0,0.0,1,Other,0,0,0,1,0,0,0,NaN,NaN,WO_B,"Write-out reason, pending review",RR3,"Re-rate requested, ok",6,AB753534,2434.10,2025-12-21 12:41:05,Saanvi Patel,"WO_D,WO_B","Desc, follow-up required, add notes,Desc, pend...",UWIYKID91,Vihaan Roy,UFKBLCMPI,Diya Khan,Reyansh Gupta,UGVNYRUIW,RPCQY6QKTC8,NaN,NaN,Arjun Verma,Rohan Singh,CA,6403,1,1.41,NaN,NaN,Open,ratingError,NaN,NaN,NCIC0GET8T,HIGH_A,High Risk A,2025-05-10,REP2,NaN,NaN,ROORXO1BDJ,E153A5QBSWRPBJEK5,2025-09-06,0.609,2025-03-04,EIBBW2ZLAOI4,LEDE8XF7KZ,CSR,1,BATCH9ITN7S,1,1,TXN55J2O7S3KK,"System recalculation, batch",5,"Underwriting decline, risk",Missing docs,"Rush, expedite",Aadhya Singh,ROORXO1BDJ,E153A5QBSWRPBJEK5,2025-09-06,Projected,1.116,EIBBW2ZLAOI4,LEDE8XF7KZ,CSR,1,BRN1N759IN,3,2,Cancellation,"System recalculation, batch",21,"System initiated, cancel","Reason for cancellation, follow-up required, a...","Sub reason, follow-up required, add notes","Rush, expedite",NJ,Aadhya Singh,1,0,Summary,1,2025-02-21 14:06:33,1,0,NaN,Current,1.178,0,0,1,279813.71,278.0,Multi Hold (2 touches),[2],2,1,NaN,None,2025-05,2025-05,Multi Hold
4,REQJ3R30ME8F840,OPP982N2ATQYY,1,PRCV37DIA5U,NB,"New Business, pending review",2025-11-09,NEW,"New, created",NaN,NaN,NaN,NaN,BG1,"Business group, follow-up required, add notes",COMM,"Commercial, fleet",P2,"Medium, standard",LEG,"System of record, follow-up required, add notes",SO53,"Sales office, needs approval, urgent",SR478,"Sales rep, ok",STD,"Standard, retail",NE,North East,D1,Division 1,2025-11-15 15:24:04,2025-11-18 15:24:04,2025-11-09 10:24:04,NaT,NaN,2025-11-10 15:24:04,NaN,NaN,NaN,PN62163160,FleetGuard,2025-11-02,2026-11-02,2025-12-20,RZ1UDBFWYJ,Diya Roy,System,LAOHSMDYVS,AC6174418,MC147623,CCO331230,Anaya Khan,Vivaan Sharma,"BlueSky Logistics, ok",NaN,NaN,NaN,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,Underwriting Request,0,0,0,0,0,1,0,NaN,NaN,WO_D,"Write-out reason, ok",RR2,"Re-rate requested, ok",3,AB820184,1540.89,2025-08-31 02:05:53,Aditya Verma,WO_A,"Desc, ok",U3UVULEMX,Diya Mehta,UBKLDSFR4,Aadhya Chatterjee,Aadhya Verma,U1U3493WX,RPCA73JGZLM,NaN,"Endorsement applied, needs approval, urgent",Ayaan Gupta,Kabir Nair,MA,2622,2,1.09,NaN,NaN,Open,editErrorMessage,NaN,NaN,NCICLA0GNZ,STD_B,Standard B,2025-11-10,REP2,"Replacement reason, pending review",NaN,RO4W7KYHQI,N9N6XCJ883DHX8BM9,2025-10-17,1.259,2025-04-16,EIBC1HH5LF6A,LED4FEJGXA,Portal,1,BATCH2ILGB0,2,2,TXNS0R2SDS8B2,"Coverage change, endorsement",15,NaN,NaN,"Rush, expedite",Anaya Das,RO4W7KYHQI,N9N6XCJ883DHX8BM9,2025-10-17,Projected,1.059,EIBC1HH5LF6A,LED4FEJGXA,Portal,1,BRNDZP6LFE,1,2,Endorsement,"Coverage change, endorsement","19,30,34,39","System initiated, cancel","Reason for cancellation, pending review","Sub reason, pending review","Rush, expedite",FL,Anaya Das,0,1,Full view,0,2025-07-31 10:52:29,3,0,NaN,Revised,0.993,1,0,1,390817.93,94.0,Straight Through,[],0,0,NaN,None,2025-11,2025-11,Straight Through

In [11]:
# 4. Key metrics and distributions

# Status counts
if "statusDescription" in df.columns:
    status_counts = df["statusDescription"].value_counts()
    display(status_counts.to_frame("Count"))

# Aging (non-completed)
aging_data = df[df["Aging_Days"].notna()].copy()
print("Non-completed cases (for aging):", len(aging_data))

# Case type distribution
case_type_counts = df["CaseType"].value_counts()
print("\nCase type counts:")
display(case_type_counts.to_frame("Count"))

# Straight / one-touch / multi-hold subsets
straight_through = df[df["CaseType"] == "Straight Through"]
one_touch = df[df["CaseType"] == "One Touch"]
multi_hold = df[df["CaseType"].str.contains("Multi Hold", na=False)]

print("\nStraight Through:", len(straight_through))
print("One Touch:", len(one_touch))
print("Multi Hold:", len(multi_hold))

# Holding time summary
holding_data = df[df["TotalHoldingTime"] > 0].copy()
print("\nCases with holding time:", len(holding_data))

# TAT data
tat_data = df[df["TAT_Days"].notna()].copy()
print("Cases with TAT:", len(tat_data))

# Median TAT overall
median_tat = tat_data["TAT_Days"].median()
print("\nMedian TAT (days):", median_tat)

                         Count
statusDescription
In progress, processing   3514
New, created              2500
Completed, issued         1955
On hold, awaiting info    1533
Cancelled, closed          498

Non-completed cases (for aging): 7547

Case type counts:

                        Count
CaseType
Straight Through         6519
Multi Hold (2 touches)   3066
Multi Hold (3 touches)    244
One Touch                 171

Straight Through: 6519
One Touch: 171
Multi Hold: 3310

Cases with holding time: 2979
Cases with TAT: 2453

Median TAT (days): 3.0

In [6]:
# 5. Visualizations (Plotly)

# Status count bar chart
if "statusDescription" in df.columns:
    fig_status = px.bar(
        status_counts.reset_index(),
        x="index",
        y="statusDescription",
        labels={"index": "Status", "statusDescription": "Count"},
        title="Status Count"
    )
    fig_status.update_xaxes(tickangle=45)
    fig_status.show()

# Aging distribution
if not aging_data.empty:
    fig_aging = px.histogram(
        aging_data,
        x="Aging_Days",
        nbins=30,
        title="Distribution of Aging Days",
        labels={"Aging_Days": "Aging (Days)", "count": "Frequency"}
    )
    fig_aging.show()

# Case type distribution (pie)
fig_case_type = px.pie(
    case_type_counts.reset_index(),
    values="CaseType",
    names="index",
    title="Case Type Distribution"
)
fig_case_type.show()

# Holding time distribution
if not holding_data.empty:
    fig_holding = px.histogram(
        holding_data,
        x="TotalHoldingTime",
        nbins=30,
        title="Distribution of Total Holding Time (Days)",
        labels={"TotalHoldingTime": "Holding Time (Days)", "count": "Frequency"}
    )
    fig_holding.show()

# TAT distribution
if not tat_data.empty:
    fig_tat = px.histogram(
        tat_data,
        x="TAT_Days",
        nbins=30,
        title="Distribution of TAT (Days)",
        labels={"TAT_Days": "TAT (Days)", "count": "Frequency"}
    )
    fig_tat.show()

# TAT buckets
tat_bucket_counts = df["TAT_Bucket"].value_counts()
fig_buckets = px.bar(
    tat_bucket_counts.reset_index(),
    x="index",
    y="TAT_Bucket",
    labels={"index": "TAT Bucket", "TAT_Bucket": "Count"},
    title="TAT Bucket Distribution"
)
fig_buckets.show()

# Median TAT by Case Type
tat_by_case_type = df.groupby("CaseType")["TAT_Days"].median().sort_values(ascending=False)
fig_tat_case = px.bar(
    tat_by_case_type.reset_index(),
    x="CaseType",
    y="TAT_Days",
    labels={"CaseType": "Case Type", "TAT_Days": "Median TAT (Days)"},
    title="Median TAT by Case Type"
)
fig_tat_case.update_xaxes(tickangle=45)
fig_tat_case.show()

# Median TAT by HoldCategory and TAT_Bucket
tat_by_hold_bucket_raw = df.groupby(["HoldCategory", "TAT_Bucket"])['TAT_Days'].median().reset_index()
if not tat_by_hold_bucket_raw.empty:
    tat_by_hold_bucket = tat_by_hold_bucket_raw.pivot(index="TAT_Bucket", columns="HoldCategory", values="TAT_Days")
    fig_tat_hold_bucket = px.bar(
        tat_by_hold_bucket.reset_index(),
        x="TAT_Bucket",
        y=[c for c in tat_by_hold_bucket.columns if c != "TAT_Bucket"],
        barmode="group",
        title="Median TAT by Hold Category and TAT Bucket",
        labels={"value": "Median TAT (Days)", "TAT_Bucket": "TAT Bucket"}
    )
    fig_tat_hold_bucket.show()

# Median TAT by HoldCategory overall
tat_by_hold_category = df.groupby("HoldCategory")["TAT_Days"].median().sort_values(ascending=False)
print("\nMedian TAT by Hold Category:")
display(tat_by_hold_category.to_frame("Median_TAT_Days"))

ValueError: Value of 'x' is not the name of a column in 'data_frame'. Expected one of ['statusDescription', 'count'] but received: index
 To use the index, pass it in directly as `df.index`.

In [ ]:
# 6. Drill-down analysis (without Streamlit UI)

# Example: change these parameters to explore different segments
DRILL_MODE = "By TAT Bucket"  # options: "Straight Through", "Multi Hold", "By TAT Bucket", "By Number of Touches"
DRILL_TAT_BUCKET = "0-5 days"  # used when DRILL_MODE == "By TAT Bucket"
DRILL_TOUCHES = 1              # used when DRILL_MODE == "By Number of Touches"

if DRILL_MODE == "Straight Through":
    drill_data = df[df["CaseType"] == "Straight Through"].copy()
elif DRILL_MODE == "Multi Hold":
    drill_data = df[df["CaseType"].str.contains("Multi Hold", na=False)].copy()
elif DRILL_MODE == "By TAT Bucket":
    drill_data = df[df["TAT_Bucket"] == DRILL_TAT_BUCKET].copy()
elif DRILL_MODE == "By Number of Touches":
    drill_data = df[df["NumberOfTouches"] == DRILL_TOUCHES].copy()
else:
    drill_data = df.copy()

print(f"Drill mode: {DRILL_MODE}, rows: {len(drill_data)}")

if not drill_data.empty:
    # Top 10 request types
    if "requestTypeDescription" in drill_data.columns:
        top_request_types = drill_data["requestTypeDescription"].value_counts().head(10)
        print("\nTop 10 Request Types:")
        display(top_request_types.to_frame("Count"))

        fig_req = px.bar(
            top_request_types.reset_index(),
            x="requestTypeDescription",
            y="count",
            labels={"requestTypeDescription": "Request Type", "count": "Count"},
            title="Top 10 Request Types (Drill-down)",
        )
        fig_req.update_xaxes(tickangle=45)
        fig_req.show()

    # Top 10 hold reasons
    if "onHoldReasonDescriptionsHistory" in drill_data.columns:
        all_hold_reasons = []
        for reasons in drill_data["onHoldReasonDescriptionsHistory"].apply(parse_separated_values):
            all_hold_reasons.extend(reasons)

        if all_hold_reasons:
            hold_reason_counts = pd.Series(all_hold_reasons).value_counts().head(10)
            print("\nTop 10 Hold Reasons:")
            display(hold_reason_counts.to_frame("Count"))

            fig_hold = px.bar(
                hold_reason_counts.reset_index(),
                x="onHoldReasonDescriptionsHistory",
                y="count",
                labels={"onHoldReasonDescriptionsHistory": "Hold Reason", "count": "Count"},
                title="Top 10 Hold Reasons (Drill-down)",
            )
            fig_hold.update_xaxes(tickangle=45)
            fig_hold.show()
else:
    print("No rows for selected drill-down.")

In [ ]:
# 7. Seasonality and location/vehicle analysis

# Seasonality by month
if "Month_Str" in df.columns:
    monthly_stats = df.groupby("Month_Str").agg({
        "requestId": "count",
        "completedDateTime": lambda x: x.notna().sum(),
        "TAT_Days": "median",
        "TotalHoldingTime": "median",
        "NumberOfTouches": "mean",
    }).rename(columns={
        "requestId": "Total_Cases",
        "completedDateTime": "Completed_Cases",
        "TAT_Days": "Median_TAT",
        "TotalHoldingTime": "Median_Holding_Time",
        "NumberOfTouches": "Avg_Touches",
    })

    monthly_stats["Completion_Rate"] = (
        monthly_stats["Completed_Cases"] / monthly_stats["Total_Cases"] * 100
    ).round(2)

    holding_rate = df.groupby("Month_Str")["TotalHoldingTime"].apply(
        lambda x: (x > 0).sum() / len(x) * 100
    ).round(2)
    monthly_stats["Holding_Rate"] = holding_rate

    print("Monthly statistics:")
    display(monthly_stats)

    fig_completion = px.line(
        monthly_stats.reset_index(),
        x="Month_Str",
        y="Completion_Rate",
        title="Monthly Completion Rate (%)",
        labels={"Month_Str": "Month", "Completion_Rate": "Completion Rate (%)"},
    )
    fig_completion.update_xaxes(tickangle=45)
    fig_completion.show()

    fig_holding_rate = px.line(
        monthly_stats.reset_index(),
        x="Month_Str",
        y="Holding_Rate",
        title="Monthly Holding Rate (%)",
        labels={"Month_Str": "Month", "Holding_Rate": "Holding Rate (%)"},
    )
    fig_holding_rate.update_xaxes(tickangle=45)
    fig_holding_rate.show()

# Location / vehicle analysis
if "numberOfLocations" in df.columns and "NumberOfVehicles" in df.columns:
    lv_data = df[(df["numberOfLocations"].notna()) & (df["NumberOfVehicles"].notna())].copy()
    if not lv_data.empty:
        location_analysis = lv_data.groupby("numberOfLocations").agg({
            "TAT_Days": "median",
            "NumberOfTouches": "mean",
            "TotalHoldingTime": "median",
            "requestId": "count",
        }).rename(columns={
            "TAT_Days": "Median_TAT",
            "NumberOfTouches": "Avg_Touches",
            "TotalHoldingTime": "Median_Holding_Time",
            "requestId": "Count",
        })

        print("\nLocation analysis:")
        display(location_analysis)

        fig_loc = px.bar(
            location_analysis.reset_index(),
            x="numberOfLocations",
            y="Median_TAT",
            title="Median TAT by Number of Locations",
            labels={"numberOfLocations": "Number of Locations", "Median_TAT": "Median TAT (Days)"},
        )
        fig_loc.show()

        vehicle_analysis = lv_data.groupby("NumberOfVehicles").agg({
            "TAT_Days": "median",
            "NumberOfTouches": "mean",
            "TotalHoldingTime": "median",
            "requestId": "count",
        }).rename(columns={
            "TAT_Days": "Median_TAT",
            "NumberOfTouches": "Avg_Touches",
            "TotalHoldingTime": "Median_Holding_Time",
            "requestId": "Count",
        })

        print("\nVehicle analysis:")
        display(vehicle_analysis)

        fig_veh = px.bar(
            vehicle_analysis.reset_index(),
            x="NumberOfVehicles",
            y="Median_TAT",
            title="Median TAT by Number of Vehicles",
            labels={"NumberOfVehicles": "Number of Vehicles", "Median_TAT": "Median TAT (Days)"},
        )
        fig_veh.show()

        # Correlations
        fig_corr_touches = px.scatter(
            lv_data,
            x="NumberOfVehicles",
            y="NumberOfTouches",
            trendline="ols",
            title="Number of Vehicles vs Number of Touches",
        )
        fig_corr_touches.show()

        fig_corr_hold = px.scatter(
            lv_data,
            x="NumberOfVehicles",
            y="TotalHoldingTime",
            trendline="ols",
            title="Number of Vehicles vs Holding Time",
        )
        fig_corr_hold.show()

In [ ]:
# 8. Holding time statistics (median highest/lowest etc.)

if not holding_data.empty:
    all_holding_times = []
    for times in holding_data["HoldingTimes"]:
        all_holding_times.extend(times)

    if all_holding_times:
        holding_times_series = pd.Series(all_holding_times)
        highest_per_case = holding_data["HoldingTimes"].apply(lambda x: max(x) if x else 0)
        lowest_per_case = holding_data["HoldingTimes"].apply(lambda x: min(x) if x else 0)

        summary = {
            "Median_Holding_Time_All": holding_times_series.median(),
            "Median_of_Highest_Holding_Time": highest_per_case.median(),
            "Median_of_Lowest_Holding_Time": lowest_per_case.median(),
            "Highest_Holding_Time_Overall": holding_times_series.max(),
            "Lowest_Holding_Time_Overall": holding_times_series.min(),
            "Average_Number_of_Touches": holding_data["NumberOfTouches"].mean(),
        }

        print("Holding time statistics:")
        display(pd.Series(summary))

        fig_holding_dist = px.histogram(
            holding_times_series,
            nbins=30,
            title="Distribution of Individual Holding Times",
            labels={"value": "Holding Time (Days)", "count": "Frequency"},
        )
        fig_holding_dist.show()

        fig_high_low = go.Figure()
        fig_high_low.add_trace(go.Box(y=highest_per_case, name="Highest per Case", boxmean="sd"))
        fig_high_low.add_trace(go.Box(y=lowest_per_case, name="Lowest per Case", boxmean="sd"))
        fig_high_low.update_layout(
            title="Highest vs Lowest Holding Times per Case",
            yaxis_title="Holding Time (Days)",
        )
        fig_high_low.show()

In [ ]:
# 9. Export all results to Excel (downloadable file)

OUTPUT_PATH = Path("underwriting_report_notebook.xlsx")

with pd.ExcelWriter(OUTPUT_PATH, engine="openpyxl") as writer:
    # Summary sheet (similar to Streamlit)
    all_holding_times_flat = []
    if not holding_data.empty:
        for times in holding_data["HoldingTimes"]:
            all_holding_times_flat.extend(times)

    highest_per_case = (
        holding_data["HoldingTimes"].apply(lambda x: max(x) if x else 0)
        if not holding_data.empty
        else pd.Series(dtype=float)
    )
    lowest_per_case = (
        holding_data["HoldingTimes"].apply(lambda x: min(x) if x else 0)
        if not holding_data.empty
        else pd.Series(dtype=float)
    )

    summary_data = {
        "Metric": [
            "Total Cases",
            "Completed Cases",
            "Median TAT (days)",
            "Median Aging (days)",
            "Straight Through Cases",
            "One Touch Cases",
            "Multi Hold Cases",
            "Median Holding Time (All)",
            "Median of Highest Holding Time",
            "Median of Lowest Holding Time",
            "Average Number of Touches",
            "Highest Holding Time (Overall)",
            "Lowest Holding Time (Overall)",
        ],
        "Value": [
            len(df),
            df["completedDateTime"].notna().sum() if "completedDateTime" in df.columns else 0,
            df["TAT_Days"].median() if "TAT_Days" in df.columns and not df["TAT_Days"].isna().all() else 0,
            df["Aging_Days"].median() if "Aging_Days" in df.columns and not df["Aging_Days"].isna().all() else 0,
            len(straight_through),
            len(one_touch),
            len(multi_hold),
            pd.Series(all_holding_times_flat).median() if all_holding_times_flat else 0,
            highest_per_case.median() if not highest_per_case.empty else 0,
            lowest_per_case.median() if not lowest_per_case.empty else 0,
            holding_data["NumberOfTouches"].mean() if not holding_data.empty else 0,
            max(all_holding_times_flat) if all_holding_times_flat else 0,
            min(all_holding_times_flat) if all_holding_times_flat else 0,
        ],
    }
    pd.DataFrame(summary_data).to_excel(writer, sheet_name="Summary", index=False)

    # Status counts
    if "status_counts" in globals():
        sc_df = status_counts.to_frame("Count").reset_index().rename(columns={"index": "Status"})
        sc_df.to_excel(writer, sheet_name="Status_Counts", index=False)

    # Case type classification
    ctc_df = case_type_counts.to_frame("Count").reset_index().rename(columns={"index": "Case_Type"})
    ctc_df.to_excel(writer, sheet_name="Case_Type_Classification", index=False)

    # TAT buckets
    tbc_df = tat_bucket_counts.to_frame("Count").reset_index().rename(columns={"index": "TAT_Bucket"})
    tbc_df.to_excel(writer, sheet_name="TAT_Buckets", index=False)

    # Median TAT by Case Type
    tat_by_case_type_df = tat_by_case_type.reset_index().rename(columns={"TAT_Days": "Median_TAT_Days"})
    tat_by_case_type_df.to_excel(writer, sheet_name="Median_TAT_by_CaseType", index=False)

    # Median TAT by Hold Category and TAT Bucket
    if "tat_by_hold_bucket_raw" in globals() and not tat_by_hold_bucket_raw.empty:
        tat_by_hold_bucket = tat_by_hold_bucket_raw.pivot(
            index="TAT_Bucket", columns="HoldCategory", values="TAT_Days"
        )
        tat_by_hold_bucket.to_excel(writer, sheet_name="Median_TAT_by_Hold_Bucket")

    # Median TAT by Hold Category
    tat_by_hold_category_df = tat_by_hold_category.to_frame("Median_TAT_Days").reset_index().rename(
        columns={"index": "Hold_Category"}
    )
    tat_by_hold_category_df.to_excel(writer, sheet_name="Median_TAT_by_HoldCategory", index=False)

    # Monthly statistics
    if "monthly_stats" in globals():
        monthly_stats.to_excel(writer, sheet_name="Monthly_Statistics")

    # Location / Vehicle analysis
    if "location_analysis" in globals():
        location_analysis.to_excel(writer, sheet_name="Location_Analysis")
    if "vehicle_analysis" in globals():
        vehicle_analysis.to_excel(writer, sheet_name="Vehicle_Analysis")

    # Holding Time Stats
    if all_holding_times_flat:
        holding_stats = {
            "Metric": [
                "Median Holding Time (All)",
                "Median of Highest Holding Time",
                "Median of Lowest Holding Time",
                "Highest Holding Time (Overall)",
                "Lowest Holding Time (Overall)",
                "Average Number of Touches",
            ],
            "Value": [
                pd.Series(all_holding_times_flat).median(),
                highest_per_case.median() if not highest_per_case.empty else 0,
                lowest_per_case.median() if not lowest_per_case.empty else 0,
                max(all_holding_times_flat),
                min(all_holding_times_flat),
                holding_data["NumberOfTouches"].mean() if not holding_data.empty else 0,
            ],
        }
        pd.DataFrame(holding_stats).to_excel(writer, sheet_name="Holding_Time_Stats", index=False)

    # Original data
    original_df.to_excel(writer, sheet_name="Original_Data", index=False)

    # Processed data (essential columns)
    essential_cols = [
        "requestId",
        "statusDescription",
        "createDateTime",
        "completedDateTime",
        "onHoldReasonDescriptionsHistory",
        "onHoldDatesHistory",
        "offHoldDatesHistory",
        "requestTypeDescription",
        "onHoldReasonDescription",
        "numberOfLocations",
        "NumberOfVehicles",
        "CaseType",
        "HoldCategory",
        "Aging_Days",
        "TAT_Days",
        "TAT_Bucket",
        "TotalHoldingTime",
        "NumberOfTouches",
        "Month_Str",
    ]
    available_cols = [c for c in essential_cols if c in df.columns]
    df[available_cols].to_excel(writer, sheet_name="Processed_Data", index=False)

print(f"Excel report written to: {OUTPUT_PATH.resolve()}")